// Danish word list for Ord Bombe
const words = [
  // Funktionsord
  "og","men","eller","for","til","fra","med","ved","over","under","bag","foran",
  "gennem","siden","end","som","når","hvis","fordi","selvom","mens","idet",
  "her","der","nu","da","så","jo","nok","vel","bare","blot","kun","ikke","også",
  "altid","aldrig","ofte","sjældent","meget","lidt","mere","mest","allerede",
  "endnu","stadig","snart","måske","vist","sikkert","faktisk","egentlig","næsten",
  "helt","netop","nemlig","desuden","alligevel","ellers","desværre","heldigvis",

  // Pronominer
  "jeg","du","han","hun","det","den","vi","de","dem","mig","dig","ham","hende",
  "os","jer","sig","man","hvem","hvad","hvilken","hvilket","hvilke","denne",
  "dette","disse","hin","hint","hine","enhver","ingen","nogen","alle","begge",

  // Verber (infinitiv)
  "arbejde","spise","drikke","sove","gå","løbe","tale","høre","se","have",
  "være","blive","komme","gøre","sige","tage","give","vide","tænke","mene",
  "ville","skulle","kunne","måtte","turde","bruge","holde","stå","sidde",
  "ligge","falde","rejse","flyve","svømme","synge","danse","læse","skrive",
  "tegne","male","spille","lytte","købe","sælge","betale","finde","miste",
  "vinde","tabe","åbne","lukke","starte","stoppe","vente","møde","kende",
  "forstå","forklare","hjælpe","lære","undervise","studere","bygge","reparere",
  "rengøre","vaske","lave","bage","koge","stege","smage","lugte","røre",
  "bære","løfte","skubbe","trække","kaste","fange","gemme","søge","vælge",
  "beslutte","prøve","forsøge","lykkes","fejle","ændre","flytte","vokse",
  "ældes","leve","elske","hade","smile","grine","græde","råbe","hviske",
  "spørge","svare","fortælle","lyve","rose","kritisere","advare","tillade",
  "forbyde","befale","bede","tilbyde","afvise","acceptere","deltage","bidrage",
  "planlægge","administrere","lede","følge","kontrollere","måle","veje",
  "tælle","opdage","opfinde","skabe","ødelægge","redde","beskytte","risikere",
  "overleve","undgå","nå","ramme","dreje","vende","krydse","passere",
  "ankomme","forlade","returnere","besøge","bo","hente","bringe","sende",
  "modtage","dele","samle","sortere","ordne","rydde","fylde","tømme",
  "hæve","sænke","øge","mindske","forbedre","bryde","knække","skære",
  "save","bore","hamre","polere","montere","installere","programmere",
  "beregne","analysere","undersøge","sammenligne","registrere","rapportere",
  "kommunikere","organisere","koordinere","evaluere","implementere","udvikle",
  "designe","skabe","producere","distribuere","markedsføre","sælge","købe",
  "handle","investere","spare","låne","betale","tjene","miste","vinde",
  "konkurrere","samarbejde","forhandle","aftale","løse","håndtere","klare",
  "overleve","trives","vokse","udvikle","modne","ældes","dø","fødes",
  "vågne","sove","drømme","hvile","slappe","trænere","øve","forberede",
  "præsentere","demonstrere","vise","bevise","forklare","beskrive","definere",
  "identificere","klassificere","kategorisere","rangere","prioritere","vælge",
  "anbefale","foreslå","advise","vejlede","coache","mentore","inspirere",
  "motivere","opmuntre","støtte","hjælpe","assistere","servicere","betjene",
  "rense","desinficere","sterilisere","konservere","opbevare","transportere",
  "levere","pakke","emballere","mærke","registrere","dokumentere","arkivere",

  // Mennesker og familie
  "mand","kvinde","barn","dreng","pige","baby","teenager","voksen","ældre",
  "familie","mor","far","søster","bror","søn","datter","forældre","bedsteforældre",
  "mormor","morfar","farmor","farfar","onkel","tante","fætter","kusine","niece",
  "nevø","svigermor","svigerfar","svigersøn","svigerdatter","svigerinde",
  "svoger","kone","mand","partner","kæreste","ven","veninde","bekkendt",
  "nabo","kollega","chef","medarbejder","elev","lærer","student","professor",

  // Kroppen
  "hoved","hår","ansigt","pande","øjenbryn","øje","næse","kind","mund",
  "læbe","tand","tunge","hage","hals","nakke","skulder","arm","albue",
  "håndled","hånd","finger","tommel","pegefinger","langfinger","ringfinger",
  "lillefinger","negl","ryg","bryst","mave","navle","hofte","lår","knæ",
  "skinneben","ankel","fod","tå","hjerne","hjerte","lunge","lever","nyre",
  "mave","tarm","blod","ben","muskel","nerve","hud","hår","negl",

  // Huset
  "hus","lejlighed","villa","cottage","sommerhus","hytte","slot","palads",
  "stue","køkken","soveværelse","badeværelse","entre","gang","kælder","loft",
  "garage","have","terrasse","altan","dør","vindue","tag","gulv","væg","loft",
  "trappe","elevator","rør","ledning","stik","kontakt","lampe","pære","pæreform",
  "sofa","stol","bord","seng","skab","reol","hylde","drawer","skuffe",
  "tæppe","gardiner","pude","dyne","lagen","håndklæde","spejl","billede",
  "ramme","vase","blomsterpotte","potteplante","kactus","orkidé",

  // Køkken og mad
  "gryde","pande","kasserolle","wok","ovn","microovn","køleskab","fryser",
  "opvaskemaskine","blender","mixer","toaster","brødrister","kaffemaskine",
  "kniv","gaffel","ske","teske","spiseske","skeegnet","skærebræt","si",
  "rivejern","rullekage","kageform","dej","mel","sukker","smør","æg","mælk",
  "fløde","yoghurt","ost","brød","rugbrød","franskbrød","bolle","toast",
  "kage","tærte","pandekage","vaffel","muffin","chokolade","slik","bolche",
  "kartoffel","ris","pasta","spaghetti","nudler","havregrød","müsli","cornflakes",
  "kød","oksekød","svinekød","lammekød","kylling","and","kalkun","pølse",
  "bacon","skinke","salami","frikadelle","bøf","kotelet","mørbrad","nakke",
  "fisk","laks","torsk","sild","makrel","ørred","tun","reje","krabbe","musling",
  "grøntsag","gulerod","løg","hvidløg","tomat","agurk","salat","spinat",
  "kål","broccoli","blomkål","ærter","bønne","mais","peberfrugt","squash",
  "radise","selleri","porre","purre","persille","dild","basilikum","timian",
  "rosmarin","mynte","oregano","koriander","sennep","peber","salt","paprika",
  "karry","ingefær","kanel","sukker","honning","sirup","eddike","olie",
  "æble","pære","banan","appelsin","citron","lime","jordbær","hindbær",
  "blåbær","brombær","ribs","kirsebær","blomme","fersken","drue","melon",
  "vandmelon","ananas","mango","kiwi","nød","mandel","hasselnød","valnød",
  "suppe","bouillon","sauce","sovs","dressing","marinade","salsa","pesto",
  "is","sorbet","flødeis","smoothie","juice","kaffe","te","kakao","sodavand",
  "øl","vin","mousserende","champagne","spiritus","snaps","vodka","whisky",
  "vand","mineralvand","danskvand","saftevand","mælk","kærnemælk",

  // Dyr
  "hund","kat","hest","ko","gris","får","ged","kanin","hamster","marsvin",
  "fugl","papegøje","kanarier","fisk","skilpadde","slange","firben","rotte",
  "mus","egern","pindsvin","ræv","ulv","bjørn","hjort","rå","hare","odder",
  "sæl","hval","delfin","hai","ørn","falk","ugle","pelikan","flamingo","pingvin",
  "elefant","løve","tiger","gepard","giraf","zebra","flodhest","næsehorn",
  "gorilla","chimpanse","orangutang","aber","krokodille","alligator","boa",
  "kobra","husorm","frø","tudse","salamander","vandmand","blæksprutte","søhest",
  "søstjerne","søpindsvin","hummer","rejer","krabbe","myg","flue","hveps","bi",
  "humlebi","sommerfugl","møl","myre","edderkop","tusindben","orm","snegl",
  "torsk","sild","makrel","laks","ørred","ål","gedde","aborre","karpe","sandart",
  "spurv","musvit","solsort","ravn","krage","skade","måge","stork","svane",
  "and","gås","perlehøne","hane","høne","kylling","due","dompap","grønirisk",

  // Natur og vejret
  "sol","måne","stjerne","sky","regn","sne","is","frost","tåge","hagl",
  "storm","orkan","torden","lyn","vind","brise","stille","varme","kulde",
  "vejr","klima","årstid","forår","sommer","efterår","vinter","dag","nat",
  "morgen","aften","middag","midnat","solopgang","solnedgang","daggry","tusmørke",
  "hav","sø","å","flod","fjord","bugt","vig","kyst","strand","klit","dune",
  "ø","halvø","næs","pynt","bjerg","bakke","dal","eng","mark","skov","hede",
  "mose","klit","ler","sand","grus","sten","klippe","kalk","kridt","jord",
  "muld","tørv","vulkan","geiser","gletcher","isbræ","oase","savanne","jungle",
  "regnskov","ørken","tundra","taiga","prærie","steppe",
  "træ","busk","blomst","græs","mos","lav","alge","tang","svamp","orm",
  "blade","bark","rod","gren","kvist","frø","kerne","bær","nød","frugt",
  "fyr","gran","eg","birk","bøg","lind","pil","poppel","ahorn","kastanje",
  "hassel","elder","hvidtjørn","hyld","brombær","hindbær","rose","pæon",
  "tulipan","påskelilje","solsikke","kornblomst","Blåklokke","Engblomme",

  // Transport
  "bil","bus","tog","metro","sporvogn","cykel","motorcykel","lastbil","varebil",
  "ambulance","brandbil","politibil","taxa","fly","helikopter","båd","skib",
  "færge","ubåd","raket","rumskib","skateboard","løbehjul","knallert",
  "motor","rat","bremse","gear","dæk","hjul","motor","bagage","billede",
  "vej","gade","motorvej","landevej","sti","gangbro","bro","tunnel",
  "station","lufthavn","havn","terminal","perron","spor","rute","linje",
  "billetautomat","billet","paskontrol","sikkerhed","check-in","boarding",

  // Tøj og mode
  "skjorte","bluse","trøje","sweater","hættetrøje","jakke","frakke","vest",
  "bukser","jeans","shorts","nederdel","kjole","dragt","jakkesæt","habit",
  "pyjamas","nattøj","badekåbe","svømmedragt","bikini","undertøj","bh",
  "strømpebukser","strømper","sokker","sko","støvler","sandaler","flip-flops",
  "sneakers","stiletter","lædersko","gummistøvler","tøfler","hjemmesko",
  "hat","kasket","hue","lue","tørklæde","halstørklæde","handsker","bælte",
  "slips","sløjfe","broche","halskæde","armbånd","ring","øreringe","ur",
  "taske","håndtaske","rygsæk","pung","tegnebog","solbriller","briller",
  "uniform","kittel","forklæde","hjelm","veste","refleksvest","regnjakke",
  "regntøj","skitøj","sportsbeklædning","badetøj","festtøj","hverdagstøj",

  // Teknologi
  "computer","laptop","tablet","smartphone","telefon","mobiltelefon","skærm",
  "tastatur","mus","printer","scanner","router","modem","server","cloud",
  "internet","netværk","wifi","bluetooth","kabel","ledning","stik","adapter",
  "batteri","oplader","headset","høretelefoner","mikrofon","højtaler","kamera",
  "software","hardware","app","program","opdatering","virus","firewall",
  "password","sikkerhed","kryptering","backup","database","server","hjemmeside",
  "browser","søgemaskine","sociale medier","streaming","download","upload",
  "email","besked","notifikation","alarm","kalender","noter","kontakter",
  "spil","konsol","controller","tastatur","joystick","VR","AR",

  // Uddannelse og arbejde
  "skole","gymnasium","universitet","college","kursus","uddannelse","studie",
  "klasse","hold","gruppe","team","afdeling","kontor","møderum","fabrik",
  "lærling","praktikant","elev","student","kandidat","bachelor","master",
  "ph.d.","forsker","professor","lektor","adjunkt","underviser","lærer",
  "rektor","dekan","rektor","direktor","chef","leder","manager","koordinator",
  "assistent","sekretær","receptionist","sagsbehandler","konsulent","rådgiver",
  "ingeniør","arkitekt","designer","kunstner","forfatter","journalist","redaktør",
  "advokat","dommer","politibetjent","soldat","brandmand","sygeplejerske",
  "læge","tandlæge","dyrlæge","farmaceut","psykolog","socialrådgiver","pædagog",
  "kok","tjener","bartender","bager","slagter","fisker","gartner","tømrer",
  "elektriker","VVS","maler","gulvlægger","tagdækker","snedker","mekaniker",
  "chauffør","pilot","kaptajn","styrmand","maskinmester","rengøringsassistent",
  "vagt","sikkerhedsvagt","portner","concierge","guide","tolk","oversætter",
  "skuespiller","musiker","sanger","danser","sportsmand","atlet","træner",
  "dommer","journalist","fotograf","stylist","makeup-artist","frisør",

  // Sport og fritid
  "fodbold","håndbold","basketball","volleyball","tennis","badminton","bordtennis",
  "svømning","løb","cykling","roning","kajak","surfing","skiløb","snowboard",
  "klatring","vandring","yoga","fitness","gym","bokse","brydning","judo",
  "karate","taekwondo","fægtning","skydning","bueskydning","golf","rugby",
  "cricket","hockey","ishockey","curling","atletik","sprint","maraton",
  "triatlon","decathlon","styrkeløft","vægtløftning","crossfit","spinning",
  "pilates","dans","ballet","hip-hop","salsa","tango","foxtrot","vals",
  "sang","musik","guitar","klaver","violin","cello","fløjte","trompet",
  "tromme","trommesæt","bas","synthesizer","keyboard","mikrofon","sang",
  "maleri","tegning","skulptur","keramik","broderi","strikning","hækling",
  "origami","fotografi","film","video","animation","digitalt","analog",
  "læsning","skrivning","poesi","prosa","roman","novelle","digt","drama",
  "teater","biograf","koncert","udstilling","museum","galleri","festival",
  "madlavning","bagning","gartneri","havebrug","fiskeri","jagt","camping",
  "rejse","sightseeing","shopping","markedsbesøg","restaurantbesøg","café",
  "brettspil","kortspil","puslespil","skak","dam","Lego","Monopoly",

  // Steder
  "by","landsby","trup","bydel","centrum","forstad","udkant","land","landsby",
  "Danmark","Sverige","Norge","Finland","Island","Grønland","Færøerne",
  "Europa","Asien","Afrika","Amerika","Australien","Antarktis","Arktis",
  "København","Aarhus","Odense","Aalborg","Esbjerg","Randers","Kolding",
  "Horsens","Vejle","Roskilde","Herning","Helsingør","Silkeborg","Næstved",
  "gade","vej","plads","torv","park","havn","strand","skov","mark","eng",
  "hotel","hostel","vandrehjem","campingplads","ferieby","resort","spa",
  "restaurant","café","bar","pub","diskoteket","natklub","biograf","teater",
  "museum","galeri","bibliotek","kirke","domkirke","moske","synagoge","tempel",
  "skole","hospital","klinik","apotek","supermarked","butik","marked","indkøbscenter",
  "tankstation","garage","værksted","fabrik","lager","kontor","rådhus",
  "politistation","brandstation","fængsel","domstol","retsbygning",
  "banegård","station","metro","lufthavn","havn","lystbådehavn","marina",
  "stadion","arena","hal","svømmehal","idrætshal","bowlinghal","kino",

  // Bygninger og rum
  "etage","sal","gang","entré","entre","foyer","lobby","reception","venteværelse",
  "kontor","møderum","konferencerum","kantines","cafeteria","kantine","toilet",
  "badeværelse","omklædningsrum","depot","lagerrum","teknisk","rum","skakt",
  "facade","gavl","mur","søjle","bjælke","konstruktion","fundament","sokkel",
  "vindueskarme","vindueskarm","karme","gesims","tagrende","nedløbsrør",
  "rende","afløb","kloake","vandmåler","elmåler","varmemåler","gasmåler",

  // Objekter og ting
  "bog","hæfte","notesbog","kalender","avis","blad","magasin","katalog","brochure",
  "brev","pakke","postkort","kuvert","frimærke","stempel","signatur",
  "nøgle","lås","hængelås","sikkerhedsnøgle","kode","pinkode","password",
  "pung","tegnebog","penge","mønt","seddel","kreditkort","betalingskort",
  "gave","indpakning","sløjfe","bånd","tape","saks","lim","nål","tråd",
  "knap","lynlås","velcro","rem","spænde","krog","søm","skrue","bolt",
  "hammer","skruetrækker","tang","sav","bor","fil","vaterpas","målebånd",
  "pærer","ledning","stik","forlænger","adapter","batteri","fjernstyring",
  "brev","notesbog","pen","blyant","viskelæder","lineal","passer","vinkelmåler",
  "maling","pensel","lærred","staffeli","papir","karton","pap","plast",
  "glas","keramik","porcelæn","metal","stål","aluminium","kobber","messing",
  "træ","bambus","kork","naturmaterialer","læder","kunststof","gummi","silikone",
  "stof","bomuld","uld","silke","hør","polyester","nylon","akryl",
  "kasse","boks","container","kurv","bakke","plade","bakke","spand",
  "flaske","krukke","glas","dåse","pose","bærepose","emballage","indpakning",
  "skål","tallerken","kop","krus","glas","flaske","kande","kaffekande",
  "ske","gaffel","kniv","spiseske","teske","skeegnet","grillspyd",

  // Adjektiver
  "god","dårlig","stor","lille","lang","kort","høj","lav","bred","smal",
  "tyk","tynd","tung","let","hurtig","langsom","stærk","svag","hård","blød",
  "varm","kold","varm","frisk","kold","sej","frisk","ny","gammel","ung","ældre",
  "smuk","grim","ren","beskidt","ryddig","rodet","stille","støjende","rolig",
  "urolig","gal","sund","syg","glad","trist","sjov","kedelig","interessant",
  "kedeligt","spændende","farlig","sikker","fri","bundet","åben","lukket",
  "mulig","umulig","nødvendig","unødvendig","vigtig","uvigtig","rigtig","forkert",
  "sand","falsk","klar","uklar","enkel","kompliceret","nem","svær","let","tung",
  "grundig","overfladisk","detaljeret","overordnet","specifik","generel",
  "direkte","indirekte","aktiv","passiv","positiv","negativ","neutral",
  "moderne","gammel","traditionel","nutidig","klassisk","antik","nostalgisk",
  "rød","blå","grøn","gul","orange","lilla","pink","hvid","sort","grå",
  "brun","beige","turkis","violet","indigo","guld","sølv","bronze","kobber",
  "lyserød","lysegrøn","lyseblå","mørkegrøn","mørkblå","mørkrød","mørkbrun",
  "gennemsigtig","uigennemsigtig","blank","mat","skinnende","mørk","lys",
  "farvefuld","farverig","monokrom","farveblind","levende","livlig","dæmpet",
  "søde","sur","bitter","salt","umami","fed","mager","krydret","mild",
  "sprød","blød","sej","hård","knasende","cremet","tyk","tynd","flydende",
  "rund","firkantet","trekant","oval","rektangulær","cylindrisk","kegleformet",
  "flad","krum","buet","ret","skæv","symmetrisk","asymmetrisk",
  "parallel","vinkelret","lodret","vandret","diagonal","cirkulær","spiralformet",

  // Tal og matematik
  "en","et","to","tre","fire","fem","seks","syv","otte","ni","ti",
  "elleve","tolv","tretten","fjorten","femten","seksten","sytten","atten","nitten",
  "tyve","tredive","fyrre","halvtreds","tres","halvfjerds","firs","halvfems",
  "hundrede","tusinde","million","milliard","billion","nul","minus","plus",
  "første","anden","tredje","fjerde","femte","sjette","syvende","ottende",
  "niende","tiende","halvt","kvart","tredjedel","fjerdedel","procent",
  "sum","differens","produkt","kvotient","brøk","decimal","potens","rod",
  "areal","volumen","omfang","diameter","radius","vinkel","grader","radian",

  // Tid
  "sekund","minut","time","dag","uge","måned","år","årti","århundrede","årtusinde",
  "øjeblik","nu","straks","snart","hurtigt","langsomt","gradvis","pludselig",
  "morgen","formiddag","middag","eftermiddag","aften","nat","midnat",
  "mandag","tirsdag","onsdag","torsdag","fredag","lørdag","søndag",
  "januar","februar","marts","april","maj","juni","juli","august",
  "september","oktober","november","december","forår","sommer","efterår","vinter",
  "i dag","i går","i morgen","nu","dengang","for nylig","snart","altid",
  "aldrig","tit","ofte","sjældent","sommetider","lejlighedsvis","regelmæssigt",

  // Sundhed og medicin
  "læge","tandlæge","sygeplejerske","patient","klinik","hospital","akutmodtagelse",
  "medicin","tablet","kapsel","sirup","salve","creme","plaster","bandage",
  "sprøjte","blodtryksmåler","termometer","stetoskop","EKG","røntgen","scanning",
  "operation","kirurgi","anæstesi","bedøvelse","narkose","genoptræning",
  "vaccination","vaccine","immunitet","antibiotika","antibiogram","recept",
  "apotek","apoteker","farmaceut","medicin","vitamin","mineral","tilskud",
  "allergi","astma","diabetes","hjertesygdom","kræft","forkølelse","influenza",
  "virus","bakterie","svamp","infektion","inflammation","feber","smerter",
  "hovedpine","maveonde","halssmerter","rygsmerter","ledsmerter","muskelspasmer",
  "stress","angst","depression","søvnløshed","udmattelse","træthed","svimmelhed",

  // Samfund og politik
  "land","stat","nation","regering","parlament","Folketing","minister","statsminister",
  "borgmester","råd","udvalg","parti","valg","afstemning","demokrati","republik",
  "monarki","konstitution","grundlov","lov","regel","regulering","vedtægt","bekendtgørelse",
  "ret","pligt","rettighed","frihed","lighed","solidaritet","bæredygtighed",
  "økonomi","budget","skat","afgift","moms","told","bolig","transport","sundhed",
  "uddannelse","socialpolitik","miljøpolitik","udenrigspolitik","forsvar","politi",
  "domstol","retssystem","fængsel","fange","kriminelt","straf","bøde","erstatning",
  "organisation","forening","klub","selskab","virksomhed","firma","iværksætter",
  "handel","industri","landbrug","fiskeri","turisme","service","teknologi",
  "forskning","innovation","patenter","ophavsret","varemærke","licens",

  // Økonomi og penge
  "penge","valuta","krone","øre","euro","dollar","pund","yen","kr","bank",
  "konto","opsparing","lån","rente","afdrag","gæld","kredit","debit","budget",
  "regnskab","faktura","kvittering","bon","moms","skat","told","gebyr","bøde",
  "investering","aktie","obligation","fond","pension","forsikring","arv","donationer",
  "løn","indkomst","udgift","profit","tab","overskud","underskud","balance",
  "markedet","børsen","handel","import","eksport","konkurrence","monopol",

  // Kommunikation og medier
  "sprog","ord","sætning","tekst","besked","kommunikation","dialog","samtale",
  "interview","debat","diskussion","præsentation","foredrag","tale","monolog",
  "nyhed","reportage","artikel","reportage","journalist","redaktør","udgiver",
  "avis","magasin","tidsskrift","blog","podcast","video","film","serie",
  "reklame","annonce","banner","plakat","flyer","folder","brochure","katalog",
  "brev","email","sms","chat","opkald","videoopkald","konference","møde",
  "sociale medier","platform","profil","følger","like","del","kommentar","hashtag",
  "nyhedsbrev","abonnement","notifikation","besked","feed","stream","live",

  // Diverse substantiver
  "problem","løsning","svar","spørgsmål","opgave","udfordring","mulighed",
  "valg","beslutning","plan","strategi","metode","teknik","redskab","værktøj",
  "princip","regel","norm","standard","kvalitet","kvantitet","mål","resultat",
  "succes","fiasko","fejl","fejltagelse","erfaring","kundskab","viden","kompetence",
  "talent","evne","færdighed","ekspertise","uddannelse","kursus","træning",
  "kreativitet","innovation","opfindelse","opdagelse","forskning","eksperiment",
  "teori","hypotese","analyse","konklusion","rapport","dokumentation","evidens",
  "tradition","kultur","identitet","værdier","normer","overbevisning","tro",
  "religion","filosofi","etik","moral","lov","retfærdighed","sandhed","ærlighed",
  "tillid","respekt","ansvar","pligt","ret","frihed","demokrati","lighed",
  "natur","miljø","klimaforandringer","bæredygtighed","energi","ressourcer",
  "affald","genbrug","genanvendelse","vedvarende energi","fossile brændstoffer",
  "sol","vind","vand","jord","luft","biodiversitet","økosystem","habitat",
  "katastrofe","krise","konflikt","krig","fred","diplomati","forhandling","aftale",
  "begivenhed","hændelse","ulykke","katastrofe","eksplosion","brand","oversvømmelse",

  // Bogstaver og symboler
  "alfa","beta","gamma","delta","epsilon","zeta","eta","theta","iota","kappa",
  "lambda","mu","nu","xi","omikron","pi","rho","sigma","tau","upsilon",
  "phi","chi","psi","omega","æ","ø","å",

  // Ekstra ord med vigtige stavelser
  // -an stavelse
  "bank","blank","bane","bland","brand","dans","fane","gang","gran","hane",
  "kanel","kran","land","mand","pande","plan","rane","rand","sang","sand",
  "span","stand","strand","tang","tank","vand","manel","panel","handel",
  "vandel","andel","mandel","kandel","vandal","sandal","signal","final",
  "kanal","anal","banal","minimal","optimal","maximal","original","universal",
  "national","regional","lokal","global","total","final","central","normal",
  "digital","spiral","mineral","liberal","general","material","mental","instrumental",

  // -en stavelse
  "ben","den","ene","ender","ens","eren","gen","hende","hen","ren","sen",
  "ten","ven","vende","gerne","kende","finde","mende","rende","sende",
  "tende","lende","bende","donde","ferne","serne","terne","verne","herne",
  "berne","nerne","derne","kerne","lerne","merne","perne","rerne","serne",
  "gerne","bestemt","cement","element","moment","talent","student","sident",
  "agent","patient","klient","resident","eksponent","komponent","argument",
  "dokument","instrument","monument","supplement","fundament","element",
  "vedvent","begivenheden","forbindelsen","forberedelsen","konklusionen",

  // -er stavelse
  "er","der","her","ger","ler","mer","per","ser","ter","ver","ner",
  "arbejder","baker","biler","boder","byger","danser","drikker","elskede",
  "finder","folder","giver","henter","holder","hører","jager","kalder",
  "kaster","knækker","koger","kommer","køber","læser","lever","løber",
  "maler","møder","nyder","pakker","peger","rejser","renser","rider",
  "samler","siger","skaber","skriver","sover","spiller","spiser","stopper",
  "tager","taler","tænker","vælger","venter","vinder","åbner","ændrer",
  "bruger","bygger","betaler","begynder","betragter","bevæger","bor","bytter",
  "der","her","jer","mer","per","ser","ter","ver","ner","ber","cer","der",

  // -et stavelse
  "et","met","ret","set","jet","net","bet","det","get","ket","let","pet",
  "alt","andet","bort","bortet","brændt","brugt","bygget","danset","drukket",
  "faktisk","fundet","givet","gjort","gået","hentet","holdt","hørt","kaldt",
  "kastet","kigget","købt","lavet","lagt","lært","løbet","malet","mødt",
  "nået","pakket","peget","rejst","ryddet","sagt","set","siddet","skrevet",
  "sovet","spillet","spist","stoppet","taget","talt","tænkt","valgt","ventet",
  "vundet","åbnet","ændret","brugt","bygget","beregnet","beskrevet","bestemt",

  // -om stavelse
  "om","dom","kom","tom","som","rom","bom","nom","lom","pom","fom",
  "blomst","fom","dom","rom","tom","kom","nom","bon","kondom","symptom",
  "problem","system","princip","kritik","musik","teknik","logik","etik",
  "fodbold","håndhold","kold","bold","fold","gold","hold","mold","solgt",
  "vold","blond","bond","fond","pond","rund","bund","fund","hund","lund",
  "mund","sund","stund","komme","dommer","sommer","nummer","gummer","trommer",
  "hammer","kammer","rammer","planter","banter","danser","lander","ander","bander",

  // -or stavelse
  "ord","bord","nord","ford","jord","gord","lord","kord","mord","sord","vord",
  "sort","port","fort","kort","dort","mort","tort","forår","forbud","forlag",
  "format","formel","formal","forskel","forstand","forstå","fortælle","fortid",
  "forslag","forsøg","fordel","forret","forrige","forsvinde","forsøge","forfølge",
  "forfatter","forklare","forkorte","forlænge","forstærke","forfærdelig",
  "forbudt","forsigtig","fornøjet","forrykt","forviklet","forvirret","forvænnet",
  "forklaret","forsvundet","fordelt","forbudt","forsket","fortsat","forbedret",

  // -st stavelse
  "sta","ste","sti","sto","stu","stå","stæ","stø",
  "stad","sted","steg","sten","step","stik","stil","stof","stok","stop",
  "stor","stov","stræk","streg","strid","strimmel","strøm","stærk","stød","stål",
  "stue","stum","stund","styke","stykke","styrke","sty","styre","støj","støv",
  "barest","bedst","dårligst","flest","flotteste","godeste","grønneste","højest",
  "hurtigst","koldest","korteste","lavest","længst","mindst","nærmest","nyeste",
  "rigeste","rodeste","simplest","skønneste","smukkeste","sødeste","strengest",
  "svageste","tyktest","tyndeste","varmest","vidste","yngste","ældste","første",

  // -sk stavelse
  "dansk","frisk","disk","dusk","fisk","flask","hvisk","kusk","musk","risk","tusk",
  "beskidt","besked","besked","beskrive","beskrivelse","beskue","beskyttet",
  "beslutte","bestille","bestemt","bestandig","bestandighed","bestå","bestemte",
  "bestemt","bestyrelse","bestøver","besøg","besøge","besøgte","besvime",
  "besvær","besværlig","betale","betjene","betyde","betydning","bevæge","bevægelse",

  // -nd stavelse
  "and","blend","blind","blond","bond","fond","fund","grind","grønd","grund",
  "hund","kind","land","lind","lund","mand","mind","mønd","nind","rind",
  "rund","sand","sind","skind","slind","sund","tand","vand","vind","wend",
  "anden","bende","finde","hende","kende","lende","mende","rende","sende",
  "vende","tvinde","spinde","binde","linde","minde","vinde","vinde","stinde",
  "vandring","sandhed","blindhed","hændelse","vinduer","brandmand","håndtere",

  // -ng stavelse
  "ang","eng","ing","ong","ung","bange","bringe","danser","fange","fringe",
  "gang","ginge","hange","inge","klingende","lange","mangle","mange","sange",
  "sang","ringe","string","svinge","tinge","vinge","yngre","yndig","yngling",
  "bringes","fanger","gangen","hangen","klinged","mangen","ringen","stingen",
  "svingen","vingen","stange","planke","blank","flanke","frankrig","banke",
  "blanke","kranke","plank","svanke","tang","tange","tangens","tangere",

  // -tr stavelse
  "træ","tro","tre","tred","trek","tren","trig","trim","trin","trio","trip",
  "trist","trop","trovs","true","trug","trum","trut","tro","trav","tryne",
  "træls","træt","træffe","trøst","træde","trøje","træning","træne","trænge",
  "trænger","træer","trøjes","trøster","trænger","træffer","træder","troskab",
  "trofast","trofæ","trods","trodsig","trommer","trold","trolley","trompet",

  // -kr stavelse
  "kram","krat","krig","krim","krop","krus","kræft","kræse","krom","kron",
  "krole","krone","kronprins","kronprinsesse","krop","krybe","krydse","kryds",
  "krydsord","krydstogt","kryptere","kristal","kristus","kristen","kristendom",
  "kritik","kritisk","kritiker","kritisere","krigszone","krigsskib","kriger",

  // -bl stavelse
  "blad","blank","blend","blind","blod","blok","blond","blood","blot","blå",
  "blæk","blæse","blød","bløde","blødende","blødgøre","blodkar","blodprop",
  "blodtryk","blomst","blomstrer","blotter","blade","bladene","blodige","blinde",
  "blandet","blankt","blandede","blandingen","blanke","blindhed","blokeret",

  // -fl stavelse
  "flaske","flot","flov","flue","flyd","flyve","flåde","flade","flak","flat",
  "flertal","flesh","flettet","flid","flik","flint","flis","flok","flom","flon",
  "flosset","flothed","flow","flydende","flygtning","flygtig","flygtighed",
  "flyvende","flyvemaskine","flygtsom","flygtede","flygtede","flygter","flokken",

  // -gr stavelse
  "grav","grå","grøn","græs","grep","grin","grå","grænse","grøde","grød",
  "grode","grow","grunt","grus","gryde","grynd","grønne","grønkål","grønland",
  "grundlag","grundlag","grundlov","grundig","grundlæggende","grundsten","grundet",
  "grunde","grundenes","grunden","grænseoverskridende","grænseflader","griber",

  // -br stavelse
  "brag","bram","bran","brat","brav","bred","bred","brev","brig","bring",
  "bris","broen","brok","brom","bron","bror","brot","brug","brun","bryd",
  "bryg","bryst","bræk","brænd","bræt","brønd","brød","brøl","brøns",
  "brand","brandalarm","branden","brander","brandmand","brandslange","brandvæsen",
  "bredde","bredde","bredbåndet","brydningspunkt","brydemæssig","brygget",

  // -pr stavelse
  "prag","pram","prat","pres","prik","prim","pris","prit","prob","prod",
  "prof","prog","prop","pros","prov","prut","præg","præk","præm","præs",
  "pragt","pragmatisk","praktik","praktisk","praktisere","præcis","præcisere",
  "præsentation","præsentere","pressen","pressebriefing","pressemøde","presse",
  "primær","primitive","primitiv","principper","principe","princip","prins",

  // -dr stavelse
  "drab","draf","drag","dram","drap","dras","drat","drav","drej","dres",
  "drev","drik","driv","drom","drop","drot","drub","drud","drug","drum",
  "drup","drus","drut","drys","dræb","dræn","dræt","drøm","drøn","drøs",
  "drama","dramatisk","dramatisere","drabet","drabsmand","drabssigtede","drager",
  "drager","dragter","drages","dragtens","drengene","drikker","drikkevarer",

  // Sammensatte ord
  "arbejdsplads","arbejdstid","arbejdsdag","arbejdsuge","arbejdsmarked",
  "boligmarked","boligpris","boligsituation","boligform","boligforening",
  "uddannelsessystem","uddannelsesniveau","uddannelsesinstitution","uddannelsesforløb",
  "sundhedssystem","sundhedsvæsen","sundhedstilstand","sundhedspleje","sundhedspolitik",
  "klimaforandringer","klimapolitik","klimamål","klimaaftale","klimakrise",
  "befolkningsvækst","befolkningstæthed","befolkningssammensætning","befolkningstal",
  "levestandard","livskvalitet","livsvilkår","livsforventning","livsstil",
  "forbrugsmønster","forbrugervalg","forbrugsgode","forbrugsvare","forbrugerpris",
  "nationaløkonomi","nationalprodukt","nationalbank","nationaldag","nationalpark",
  "verdensrekord","verdenskort","verdenshistorie","verdensomspændende","verdensklasse",
  "menneskeret","menneskerettigheder","menneskehandel","menneskeskabte","menneskemasse",

  // Mere almindelige ord og fraser
  "rigtig","forkert","sandt","falsk","godt","dårligt","nyt","gammelt","ungt","ældet",
  "lille","store","lang","kort","høj","lav","bred","smal","tyk","tynd",
  "hurtig","langsom","stærk","svag","hård","blød","varm","kold","frisk","tør",
  "glad","trist","vred","bange","overrasket","skuffet","tilfreds","utilfreds",
  "træt","udhvilet","sulten","mæt","tørstig","frisk","syg","rask","ked","lykkelig",
  "venlig","uvenlig","høflig","uhøflig","beskeden","arrogant","ærlig","uærlig",
  "modig","fej","generøs","grådig","flittig","doven","kreativ","kedelig",
  "intelligent","dum","klog","uerfaren","erfaren","dygtig","dårlig","god",
  "smuk","grim","ren","beskidt","ordentlig","rodet","stille","støjende","rolig",
  "sjov","kedelig","spændende","kedelig","interessant","uinteressant",
  "vigtig","uvigtig","nødvendig","unødvendig","mulig","umulig","rimelig","urimelig",
  "naturlig","unaturlig","normal","unormal","typisk","atypisk","speciel","general",
  "konkret","abstrakt","praktisk","teoretisk","simpel","kompliceret","klar","uklar",
  "direkte","indirekte","åben","lukket","fri","begrænset","fleksibel","rigid",
  "moderne","gammeldags","traditionel","progressiv","konservativ","liberal",
  "professionel","amatør","ekspert","nybegynder","erfaren","uerfaren","kvalificeret",
  "ukvalificeret","kompetent","inkompetent","effektiv","ineffektiv","produktiv",
  "uproduktiv","aktiv","passiv","energisk","træt","entusiastisk","ligegyldig",

  // Yderligere verber (bøjet)
  "arbejder","spiser","drikker","sover","går","løber","taler","hører","ser","har",
  "er","bliver","kommer","gør","siger","tager","giver","ved","tænker","mener",
  "vil","skal","kan","må","tør","bruger","holder","står","sidder","ligger",
  "falder","rejser","flyver","svømmer","synger","danser","læser","skriver",
  "tegner","maler","spiller","lytter","køber","sælger","betaler","finder",
  "mister","vinder","taber","åbner","lukker","starter","stopper","venter",
  "møder","kender","forstår","forklarer","hjælper","lærer","bygger","reparerer",
  "vasker","laver","bager","koger","steger","smager","lugter","rører","bærer",
  "løfter","skubber","trækker","kaster","fanger","gemmer","søger","vælger",
  "beslutte","prøver","forsøger","lykkes","fejler","ændrer","flytter","vokser",
  "lever","elsker","hader","smiler","griner","græder","råber","hviske","spørger",
  "svarer","fortæller","lyver","roser","kritiserer","advarer","tillader","forbyder",
  "befaler","beder","tilbyder","afviser","accepterer","deltager","bidrager",
  "planlægger","administrerer","leder","følger","kontrollerer","måler","vejer",
  "tæller","opdager","opfinder","skaber","ødelægger","redder","beskytter",
  "risikerer","overlever","undgår","når","rammer","drejer","vender","krydser",
  "passerer","ankommer","forlader","returnerer","besøger","bor","henter",
  "bringer","sender","modtager","deler","samler","sorterer","ordner","rydder",

  // Endnu mere ord
  "årsag","virkning","sammenhæng","konsekvens","resultat","effekt","indvirkning",
  "fordel","ulempe","styrke","svaghed","mulighed","trussel","risiko","udfordring",
  "krav","behov","ønske","mål","formål","hensigt","vision","mission","strategi",
  "metode","tilgang","teknik","procedure","proces","system","struktur","organisation",
  "model","teori","princip","paradigme","ramme","kontekst","perspektiv","vinkel",
  "standpunkt","synspunkt","holdning","mening","opfattelse","forståelse","fortolkning",
  "analyse","vurdering","evaluering","bedømmelse","kritik","feedback","respons",
  "spørgsmål","svar","forklaring","beskrivelse","definition","eksempel","illustration",
  "argument","begrundelse","bevis","dokumentation","evidens","kilde","reference",
  "sammenligning","kontrast","forskel","lighed","parallel","analogt","metafor",
  "symbol","tegn","signal","indikator","markør","mærke","etiket","kategori",
  "type","variant","version","udgave","form","format","stil","design","layout",
  "indhold","form","struktur","komposition","opbygning","opstilling","arrangering",
  "præsentation","formidling","kommunikation","transmission","modtagelse","fortolkning",
  "oversættelse","tilpasning","transformation","forandring","udvikling","ændring",
  "forbedring","forringelse","optimering","effektivisering","rationalisering",
  "digitalisering","automatisering","modernisering","reform","revolution","evolution",

  // Mere specifikke danske ord
  "hygge","hyggelig","uhyggelig","hyggesnak","hyggekrog","hyggetime","hyggestund",
  "smørrebrød","rugbrød","leverpostej","medisterpølse","flæskesteg","æbleskiver",
  "brunsviger","hindbærsnitter","kanelsnurrer","wienerbrød","fastelavnsbolle",
  "janteloven","jante","folkelighed","frisind","velfærdsstat","velfærdssamfund",
  "Grundtvig","Andersen","Kierkegaard","folkekirke","folkeskole","folkehøjskole",
  "landsting","folketing","Christiansborg","statsminister","dronning","prins",
  "Bornholm","Fyn","Sjælland","Jylland","Lolland","Falster","Langeland","Mors",
  "Limfjord","Vejle Fjord","Isefjord","Roskilde Fjord","Øresund","Storebælt",
  "Lillebælt","Kattegat","Skagerrak","Nordsø","Vesterhavet","Østersøen",

  // Ord med specielle bogstaver
  "æble","ære","ærlig","ærinde","ærbar","ærg","ærmet","ærtesuppe","ærter",
  "ø","øst","øst","øvre","øvrig","øjeblik","øjne","øl","øre","øret","ørn",
  "øve","øves","øvelses","øvrige","ørken","ørred","ørsten","ørkenvandring",
  "å","åben","åbent","åbner","åbning","åbenlyst","åbenmundet","åbenbar",
  "åndedræt","år","årsag","årstal","årti","århundrede","årstid","årvågen",
  "kæde","kælder","kæmpe","kæmper","kærlighed","kærtegn","kæft","kæledyr",
  "kæmpelejlighed","kæreste","kæreste","kærlighed","kærlighed","kærlighedserklæring",
  "mænd","mærke","mærkelig","mæske","mætte","mælk","mærke","mærkelig","mænd",
  "næse","næsten","nætter","nævne","nøgle","nøjsom","nøjagtig","nøle","nødt",
  "næsen","næstet","nævner","nøgler","nøjsomhed","nøjagtighed","nøler","nødsituation",
  "grøn","grød","grønne","grødagtig","grønkål","grønland","grønlænder","grøntsag",
  "sød","søde","søger","søster","søvn","sø","søer","søfolk","søhest","søm",
  "løse","løb","løber","løg","løn","løsning","løse","løv","løvtræ","løvfald",
  "tøj","tøjle","tørt","tøse","tøv","tøve","tøven","tømt","tønde","tørst",
  "rød","røde","røg","røget","rør","rørende","røre","rørt","røveri","røde",
  "blåt","blød","bløde","blødende","blødgøre","blæse","blæst","blæk","blære",

  // Yderligere sammensatte ord
  "fodboldbane","fodboldkamp","fodboldhold","fodboldspiller","fodboldlandskamp",
  "håndboldkamp","håndboldspiller","håndboldhold","håndboldmål","håndbolddomme",
  "svømmehallen","svømmeklub","svømmevest","svømmertræning","svømmestadion",
  "løbesko","løbetræning","løbekoncurrence","løbebane","løbetøj","løbetid",
  "cykelsti","cykeltur","cykelbane","cykelklub","cykelsport","cykelrute",
  "haveparty","havefest","havemøbler","havearbejde","haveredskaber","haveplanterne",
  "middagsretten","middagsmad","middagsselskab","middagsgæst","middagshvile",
  "morgenkaffe","morgenbrød","morgenmad","morgenavisen","morgengymnastik",
  "aftenavisen","aftensmad","aftenselskab","aftenmøde","aftengæster","aftennyheder",
  "weekendtur","weekendmad","weekendplan","weekendaktivitet","weekendshopping",
  "vinterferie","sommerferie","efterårsferie","påskeferie","juleferie","pinseferie",
  "højtid","helligdag","fridag","feriedag","arbejdsdag","hverdagen","weekend",
  "nytårsdag","nytårsforsæt","nytårsfest","nytårsaften","nytårskoncert","nytår",
  "påskeæg","påskedagene","påskehøjtid","påskelørdag","langfredag","skærtorsdag",
  "juleaften","juledag","juleaften","julegave","juletræ","julefrokost","julefest",
  "grundlovsdag","mortensdag","halloween","fastelavn","morsdag","farsdag",
  "bryllupsdag","fødselsdag","konfirmation","barnedåb","begravelse","bisættelse",

  // Ekstra verber og adjektiver
  "interessant","fascinerende","beundringsværdig","imponerende","overraskende",
  "fantastisk","vidunderlig","mærkelig","speciel","usædvanlig","almindelig",
  "hverdagslig","simpel","enkel","kompliceret","kompleks","indviklet","forvirret",
  "klart","tydeligt","uklart","tvetydigt","præcis","nøjagtig","unøjagtig",
  "detaljeret","overordnet","specifik","generel","konkret","abstrakt","praktisk",
  "teoretisk","akademisk","videnskabelig","teknisk","administrativ","juridisk",
  "politisk","social","kulturel","historisk","geografisk","biologisk","kemisk",
  "fysisk","matematisk","statistisk","digital","analog","mekanisk","elektrisk",
  "elektronisk","magnetisk","akustisk","optisk","termisk","hydraulisk","pneumatisk",
  "industriel","kommerciel","professionel","amatørmæssig","kreativ","destruktiv",
  "konstruktiv","produktiv","effektiv","ineffektiv","aktiv","passiv","reaktiv",
  "proaktiv","intuitiv","analytisk","syntetisk","induktiv","deduktiv","empirisk",
  "rationel","irrationel","logisk","ulogisk","konsekvent","inkonsekvent",
  "systemisk","systematisk","kaotisk","ordnet","struktureret","ustruktureret",

  // Ord der mangler - ekstra
  "dygtig","begavet","talentfuld","kreativ","innovativ","nytænkende","fremadrettet",
  "ambitiøs","målrettet","fokuseret","disciplineret","organiseret","metodisk",
  "fleksibel","adaptiv","tilpasningsdygtig","robust","modstandsdygtig","stabil",
  "pålidelig","troværdig","autentisk","gennemsigtig","ansvarlig","etisk","moralsk",
  "empatisk","medfølende","hjælpsom","samarbejdsorienteret","teamorienteret",
  "kommunikativ","veltalende","overbevisende","inspirerende","motiverende",
  "engageret","entusiastisk","passioneret","dedikeret","standhaftig","vedholdende",

  // Vigtige ord til spilbarhed
  "spilleplade","spillekort","spillebrik","spillepioner","spilleomgang","spillerunde",
  "pointtavle","resultatliste","scoreboard","topscorer","mester","vinder","taber",
  "finalist","semifinalist","kvartfinalist","deltager","konkurrent","modstander",
  "hold","partner","makker","kollega","teamwork","samarbejde","konkurrence",
  "turnering","stævne","kamp","match","set","runde","omgang","halvleg",
  "overtid","straffe","frislag","indkast","hjørnespark","straffespark",
  "offside","frispark","gult kort","rødt kort","udvisning","dommer","linje",
  "stadion","bane","mål","boldmål","basketkurv","net","udstyr","trøje",
  "shorts","støvler","handske","hjelm","beskytter","rygsæk","flaske","håndklæde",
];

module.exports = words;
